version: "3"
services:
  web:
    build: .
    ports:
      - "8086:8000"
    container_name: social-context-staging
    environment:
      - FLASK_ENV=production
      - SCHEDULE_IN_HOURS=1
      - APP_ID_1=wJmfVFHlyj
      - APP_ID_2=
      - APP_ID_3=
      - APP_ID_4=
      - APP_ID_5=
      - APP_ID_6=
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - HUB_API=https://wenet.u-hopper.com/dev/hub/frontend
      - PROFILE_MANAGER_API=https://ardid.iiia.csic.es/wenet/profile-manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/dev/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://ardid.iiia.csic.es/wenet/interaction-protocol-engine
      - CELERY_BROKER_URL=redis://redis:6379
      - FLASK_DEBUG=0
    volumes:
      - dbvolumestaging:/app/FlaskApp/db
      - dbvolumestaging:/app/FlaskApp/logs
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  celery_beat:
    build:
      context: .
    image: flask_celery_beat
    command: celery -A FlaskCelery.tasks.celery beat -l INFO --logfile=FlaskCelery/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - SCHEDULE_IN_HOURS=1
      - APP_ID_1=wJmfVFHlyj
      - APP_ID_2=
      - APP_ID_3=
      - APP_ID_4=
      - APP_ID_5=
      - APP_ID_6=
      - HUB_API=https://wenet.u-hopper.com/dev/hub/frontend
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - PROFILE_MANAGER_API=https://ardid.iiia.csic.es/wenet/profile-manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/dev/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://ardid.iiia.csic.es/wenet/interaction-protocol-engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolumestaging:/app/FlaskCelery/logs
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    image: flask_celery_worker
    command: celery -A FlaskCelery.tasks.celery worker -l INFO --logfile=FlaskCelery/logs/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - SCHEDULE_IN_HOURS=1
      - APP_ID_1=wJmfVFHlyj
      - APP_ID_2=
      - APP_ID_3=
      - APP_ID_4=
      - APP_ID_5=
      - APP_ID_6=
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - HUB_API=https://wenet.u-hopper.com/dev/hub/frontend
      - PROFILE_MANAGER_API=https://ardid.iiia.csic.es/wenet/profile-manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/dev/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://ardid.iiia.csic.es/wenet/interaction-protocol-engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolumestaging:/app/FlaskCelery/logs
    depends_on:
      - redis
volumes:
  dbvolumestaging:

