version: "3"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - "8081:5000"
    container_name: social-context-dev
    env_file:
      - ./env.prod

