version: "3"
services:
  web:
    build: .
    ports:
      - "8086:5000"
    container_name: social-context-staging
    environment:
      - FLASK_ENV= development
      - COMP_AUTH_KEY= zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
    env_file:
      - ./dev.env
    volumes:
      - dbvolumestaging:/app/FlaskApp/db
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
    image: flask_celery_example_celery_worker
    command: celery -A FlaskCelery.tasks.celery worker -l INFO
    env_file:
      - ./dev.env
    environment:
      - FLASK_APP=app
    depends_on:
      - redis

volumes:
  dbvolumestaging:

