version: "3"
services:
  web:
    build: .
    ports:
      - "8081:5000"
    container_name: social-context-dev
    environment:
      - FLASK_ENV= development
      - COMP_AUTH_KEY= zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
    env_file:
      - ./dev.env
    volumes:
      - dbvolume:/app/db
volumes:
  dbvolume:

