version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8000"
    container_name: social-context-prod
    environment:
      - FLASK_ENV=production
      - SCHEDULE_IN_HOURS=1
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - HUB_API=https://internetofus.u-hopper.com/beta/hub/frontend
      - PROFILE_MANAGER_API=https://internetofus.u-hopper.com/beta/profile_manager
      - TASK_MANAGER_API=https://internetofus.u-hopper.com/beta/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://internetofus.u-hopper.com/beta/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
      - FLASK_DEBUG=0
    volumes:
      - dbvolumesprod:/app/FlaskApp/db
      - dbvolumesprod:/app/FlaskApp/logs
    depends_on:
      - redis
      - celery_beat
      - celery_worker

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  celery_beat:
    build:
      context: .
    image: flask_celery_beat
    command: celery -A FlaskCelery.tasks.celery beat -l INFO --logfile=FlaskCelery/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - SCHEDULE_IN_HOURS=1
      - HUB_API=https://internetofus.u-hopper.com/beta/hub/frontend
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - PROFILE_MANAGER_API=https://internetofus.u-hopper.com/beta/profile_manager
      - TASK_MANAGER_API=https://internetofus.u-hopper.com/beta/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://internetofus.u-hopper.com/beta/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolumesprod:/app/FlaskCelery/logs
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    image: flask_celery_worker_prod
    command: celery -A FlaskCelery.tasks.celery worker -l INFO --logfile=FlaskCelery/logs/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - SCHEDULE_IN_HOURS=1
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - HUB_API=https://internetofus.u-hopper.com/beta/hub/frontend
      - PROFILE_MANAGER_API=https://internetofus.u-hopper.com/beta/profile_manager
      - TASK_MANAGER_API=https://internetofus.u-hopper.com/beta/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://internetofus.u-hopper.com/beta/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolumesprod:/app/FlaskCelery/logs
    depends_on:
      - redis
      - celery_beat
volumes:
  dbvolumesprod:
