version: "3"
services:
  web:
    build: .
    ports:
      - "8081:8000"
    container_name: social-context-beta
    environment:
      - FLASK_ENV=production
      - COMP_AUTH_KEY=pa0th9Qo1SJrPb9x3agmLbIGOxZO4aFuWsvGJzsqAJc
      - HUB_API=https://wenet.u-hopper.com/beta/hub/frontend
      - PROFILE_MANAGER_API=https://wenet.u-hopper.com/beta/profile_manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/beta/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://wenet.u-hopper.com/beta/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
      - FLASK_DEBUG=0
    volumes:
      - dbvolumestaging:/app/FlaskApp/db
      - dbvolumestaging:/app/FlaskApp/logs
    depends_on:
      - redis
      - celery_beat
      - celery_worker

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  celery_beat:
    build:
      context: .
    image: flask_celery_beat
    command: celery -A FlaskCelery.tasks.celery beat -l INFO --logfile=FlaskCelery/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - HUB_API=https://wenet.u-hopper.com/dev/hub/frontend
      - COMP_AUTH_KEY=zJ9fwKb1CzeJT7zik_2VYpIBc_yclwX4Vd7_lO9sDlo
      - PROFILE_MANAGER_API=https://wenet.u-hopper.com/dev/profile_manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/dev/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://wenet.u-hopper.com/dev/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolume:/app/FlaskCelery/logs
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    image: flask_celery_worker
    command: celery -A FlaskCelery.tasks.celery worker -l INFO --logfile=FlaskCelery/logs/social-context-builder-celery.log
    restart: always
    environment:
      - FLASK_APP=app
      - COMP_AUTH_KEY=pa0th9Qo1SJrPb9x3agmLbIGOxZO4aFuWsvGJzsqAJc
      - HUB_API=https://wenet.u-hopper.com/beta/hub/frontend
      - PROFILE_MANAGER_API=https://wenet.u-hopper.com/beta/profile_manager
      - TASK_MANAGER_API=https://wenet.u-hopper.com/beta/task_manager
      - INTERACTION_PROTOCOL_ENGINE=https://wenet.u-hopper.com/beta/interaction_protocol_engine
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - dbvolumestaging:/app/FlaskCelery/logs
    depends_on:
      - redis
      - celery_beat
volumes:
  dbvolumestaging:

